name: own_portfolio
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed: ^2.1.0+1
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^1.0.4
  json_serializable: ^6.3.2
  freezed_annotation: ^2.1.0
  intl: ^0.17.0
  fl_chart: ^0.55.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.0.1
  build_runner: ^2.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
