name: Github Actions CI

on:
  push:
    branched:
      - main

jobs:
  Flutter-Test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.2'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test
